class AuditModule:
    SALES = "sales"
    PAYMENTS = "payments"
    CASH_REGISTER = "cash_register"
    INVENTORY = "inventory"
    PURCHASES = "purchases"
    BILLING = "billing"
    BUSINESS_CONFIG = "business_config"


class AuditEventType:
    SALE_COMPLETED = "SALE_COMPLETED"
    SALE_CANCELLED = "SALE_CANCELLED"
    SALE_RETURN_COMPLETED = "SALE_RETURN_COMPLETED"
    SALE_RETURN_CANCELLED = "SALE_RETURN_CANCELLED"

    PAYMENT_COMPLETED = "PAYMENT_COMPLETED"
    PAYMENT_REFUNDED = "PAYMENT_REFUNDED"
    PAYMENT_CANCELLED = "PAYMENT_CANCELLED"
    SALE_ON_ACCOUNT_REGISTERED = "SALE_ON_ACCOUNT_REGISTERED"

    CASH_SESSION_OPENED = "CASH_SESSION_OPENED"
    CASH_IN = "CASH_IN"
    CASH_OUT = "CASH_OUT"
    CASH_ADJUSTED = "CASH_ADJUSTED"
    CASH_COUNTED = "CASH_COUNTED"
    CASH_SESSION_CLOSED = "CASH_SESSION_CLOSED"

    STOCK_INITIALIZED = "STOCK_INITIALIZED"
    STOCK_ADJUSTED = "STOCK_ADJUSTED"
    STOCK_ADJUSTMENT_CANCELLED = "STOCK_ADJUSTMENT_CANCELLED"

    PURCHASE_CREATED = "PURCHASE_CREATED"
    PURCHASE_ORDERED = "PURCHASE_ORDERED"
    PURCHASE_RECEIVED = "PURCHASE_RECEIVED"
    PURCHASE_CANCELLED = "PURCHASE_CANCELLED"

    BILLING_DOCUMENT_ISSUED = "BILLING_DOCUMENT_ISSUED"
    BILLING_DOCUMENT_SUBSTITUTED = "BILLING_DOCUMENT_SUBSTITUTED"
    BILLING_DOCUMENT_RECTIFIED = "BILLING_DOCUMENT_RECTIFIED"

    BUSINESS_CONFIG_CHANGED = "BUSINESS_CONFIG_CHANGED"


EVENT_MODULES = {
    AuditEventType.SALE_COMPLETED: AuditModule.SALES,
    AuditEventType.SALE_CANCELLED: AuditModule.SALES,
    AuditEventType.SALE_RETURN_COMPLETED: AuditModule.SALES,
    AuditEventType.SALE_RETURN_CANCELLED: AuditModule.SALES,
    AuditEventType.PAYMENT_COMPLETED: AuditModule.PAYMENTS,
    AuditEventType.PAYMENT_REFUNDED: AuditModule.PAYMENTS,
    AuditEventType.PAYMENT_CANCELLED: AuditModule.PAYMENTS,
    AuditEventType.SALE_ON_ACCOUNT_REGISTERED: AuditModule.PAYMENTS,
    AuditEventType.CASH_SESSION_OPENED: AuditModule.CASH_REGISTER,
    AuditEventType.CASH_IN: AuditModule.CASH_REGISTER,
    AuditEventType.CASH_OUT: AuditModule.CASH_REGISTER,
    AuditEventType.CASH_ADJUSTED: AuditModule.CASH_REGISTER,
    AuditEventType.CASH_COUNTED: AuditModule.CASH_REGISTER,
    AuditEventType.CASH_SESSION_CLOSED: AuditModule.CASH_REGISTER,
    AuditEventType.STOCK_INITIALIZED: AuditModule.INVENTORY,
    AuditEventType.STOCK_ADJUSTED: AuditModule.INVENTORY,
    AuditEventType.STOCK_ADJUSTMENT_CANCELLED: AuditModule.INVENTORY,
    AuditEventType.PURCHASE_CREATED: AuditModule.PURCHASES,
    AuditEventType.PURCHASE_ORDERED: AuditModule.PURCHASES,
    AuditEventType.PURCHASE_RECEIVED: AuditModule.PURCHASES,
    AuditEventType.PURCHASE_CANCELLED: AuditModule.PURCHASES,
    AuditEventType.BILLING_DOCUMENT_ISSUED: AuditModule.BILLING,
    AuditEventType.BILLING_DOCUMENT_SUBSTITUTED: AuditModule.BILLING,
    AuditEventType.BILLING_DOCUMENT_RECTIFIED: AuditModule.BILLING,
    AuditEventType.BUSINESS_CONFIG_CHANGED: AuditModule.BUSINESS_CONFIG,
}

AUDIT_MODULES = frozenset(EVENT_MODULES.values())
AUDIT_EVENT_TYPES = frozenset(EVENT_MODULES)
