# Generated by Django 5.2.12 on 2026-07-29 18:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cash_register", "0001_initial"),
        ("catalog", "0003_alter_product_options_and_more"),
        ("core", "0001_initial"),
        (
            "customers",
            "0002_remove_customeraccountentry_chk_custentry_type_sign_and_more",
        ),
        ("stores", "0005_store_is_default_alter_store_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("open", "Abierta"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                            ("returned", "Devuelta"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "document_type_requested",
                    models.CharField(
                        choices=[
                            ("ticket", "Ticket"),
                            ("invoice", "Factura"),
                            ("none", "Sin documento solicitado"),
                        ],
                        default="ticket",
                        help_text="Indica si el cliente solicita ticket, factura o ningún documento concreto. Billing decidirá posteriormente el tipo fiscal definitivo.",
                        max_length=20,
                        verbose_name="Documento solicitado",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Pendiente de pago"),
                            ("partial", "Pagada parcialmente"),
                            ("paid", "Pagada"),
                            ("refunded", "Reembolsada"),
                        ],
                        db_index=True,
                        default="unpaid",
                        max_length=20,
                        verbose_name="Estado del pago",
                    ),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        help_text="Suma de bases antes de descuentos e impuestos.",
                        max_digits=14,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        help_text="Suma de los descuentos aplicados a la venta.",
                        max_digits=14,
                        verbose_name="Descuento total",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        help_text="Suma de impuestos calculados en las líneas.",
                        max_digits=14,
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        help_text="Importe final que debe pagar el cliente.",
                        max_digits=14,
                        verbose_name="Total",
                    ),
                ),
                (
                    "pending_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        help_text="Importe que todavía queda por cobrar.",
                        max_digits=14,
                        verbose_name="Importe pendiente",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha y hora en la que la venta quedó completada.",
                        null=True,
                        verbose_name="Fecha de finalización",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="core.business",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "cash_register",
                    models.ForeignKey(
                        blank=True,
                        help_text="Caja desde la que se realiza la venta. Puede quedar vacía cuando el negocio no exige trabajar con caja.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="cash_register.cashregister",
                        verbose_name="Caja",
                    ),
                ),
                (
                    "cash_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sesión de caja asociada a la venta. Será obligatoria cuando la configuración exija caja abierta.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="cash_register.cashsession",
                        verbose_name="Sesión de caja",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_closed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cerrada por",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cliente asociado a la venta. Es opcional para un ticket normal, pero será necesario para determinados documentos fiscales.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="customers.customer",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_opened",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Abierta por",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="stores.store",
                        verbose_name="Tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="SaleLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_name",
                    models.CharField(
                        help_text="Nombre congelado en el momento de la venta.",
                        max_length=180,
                        verbose_name="Nombre del producto",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="SKU congelado en el momento de la venta.",
                        max_length=80,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Cantidad vendida. Permite unidades, peso, horas o servicios.",
                        max_digits=14,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unidad congelada: ud, kg, h, servicio, etc.",
                        max_length=20,
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "unit_base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio base unitario sin impuestos aplicado en la venta.",
                        max_digits=12,
                        verbose_name="Precio unitario sin IVA",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Importe total descontado en esta línea.",
                        max_digits=14,
                        verbose_name="Descuento de la línea",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Porcentaje de impuesto congelado en la venta.",
                        max_digits=5,
                        verbose_name="Tipo impositivo",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Importe de impuesto calculado para la línea.",
                        max_digits=14,
                        verbose_name="Cuota de impuesto",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Importe final de la línea con descuentos e impuestos.",
                        max_digits=14,
                        verbose_name="Total de la línea",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_lines",
                        to="core.business",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Producto del catálogo que originó la línea. Los datos históricos se conservan aunque esta relación desaparezca.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_lines",
                        to="catalog.product",
                        verbose_name="Producto original",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.sale",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de venta",
                "verbose_name_plural": "Líneas de venta",
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SaleReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.TextField(
                        help_text="Motivo comercial de la devolución. Será necesario para la trazabilidad y la rectificativa.",
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        help_text="Importe total de las líneas devueltas.",
                        max_digits=14,
                        verbose_name="Total devuelto",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_returns",
                        to="core.business",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_returns_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creada por",
                    ),
                ),
                (
                    "original_sale",
                    models.ForeignKey(
                        help_text="Venta sobre la que se realiza la devolución.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="sales.sale",
                        verbose_name="Venta original",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_returns",
                        to="stores.store",
                        verbose_name="Tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devolución de venta",
                "verbose_name_plural": "Devoluciones de venta",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="SaleReturnLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Cantidad devuelta de la línea original.",
                        max_digits=14,
                        verbose_name="Cantidad devuelta",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Importe económico correspondiente a la cantidad devuelta.",
                        max_digits=14,
                        verbose_name="Importe devuelto",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_return_lines",
                        to="core.business",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "original_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="sales.saleline",
                        verbose_name="Línea original",
                    ),
                ),
                (
                    "return_doc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.salereturn",
                        verbose_name="Devolución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de devolución",
                "verbose_name_plural": "Líneas de devolución",
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["business", "store", "status"], name="idx_sale_bus_store_status"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["business", "payment_status"], name="idx_sale_bus_payment"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["business", "created_at"], name="idx_sale_bus_created"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["business", "customer"], name="idx_sale_bus_customer"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal_amount__gte", Decimal("0.00"))),
                name="chk_sale_subtotal_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", Decimal("0.00"))),
                name="chk_sale_discount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", Decimal("0.00"))),
                name="chk_sale_tax_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", Decimal("0.00"))),
                name="chk_sale_total_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("pending_amount__gte", Decimal("0.00"))),
                name="chk_sale_pending_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("pending_amount__lte", models.F("total_amount"))),
                name="chk_sale_pending_lte_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "completed"), _negated=True),
                    ("completed_at__isnull", False),
                    _connector="OR",
                ),
                name="chk_sale_completed_has_date",
            ),
        ),
        migrations.AddIndex(
            model_name="saleline",
            index=models.Index(
                fields=["business", "sale"], name="idx_saleline_bus_sale"
            ),
        ),
        migrations.AddIndex(
            model_name="saleline",
            index=models.Index(
                fields=["business", "product"], name="idx_saleline_bus_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", Decimal("0.000"))),
                name="chk_saleline_quantity_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_base_price__gte", Decimal("0.00"))),
                name="chk_saleline_price_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", Decimal("0.00"))),
                name="chk_saleline_discount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_rate__gte", Decimal("0.00"))),
                name="chk_saleline_tax_rate_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", Decimal("0.00"))),
                name="chk_saleline_tax_amount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("line_total__gte", Decimal("0.00"))),
                name="chk_saleline_total_gte_0",
            ),
        ),
        migrations.AddIndex(
            model_name="salereturn",
            index=models.Index(
                fields=["business", "store", "status"], name="idx_salereturn_bus_store"
            ),
        ),
        migrations.AddIndex(
            model_name="salereturn",
            index=models.Index(
                fields=["business", "original_sale"], name="idx_salereturn_bus_sale"
            ),
        ),
        migrations.AddIndex(
            model_name="salereturn",
            index=models.Index(
                fields=["business", "created_at"], name="idx_salereturn_bus_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturn",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", Decimal("0.00"))),
                name="chk_salereturn_total_gte_0",
            ),
        ),
        migrations.AddIndex(
            model_name="salereturnline",
            index=models.Index(
                fields=["business", "return_doc"], name="idx_returnline_bus_return"
            ),
        ),
        migrations.AddIndex(
            model_name="salereturnline",
            index=models.Index(
                fields=["business", "original_line"], name="idx_returnline_bus_line"
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturnline",
            constraint=models.UniqueConstraint(
                fields=("return_doc", "original_line"), name="uniq_return_original_line"
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturnline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", Decimal("0.000"))),
                name="chk_returnline_quantity_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturnline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", Decimal("0.00"))),
                name="chk_returnline_amount_gte_0",
            ),
        ),
    ]
