# Generated by Django 5.2.12 on 2026-07-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salereturnline",
            name="restock",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el producto vuelve al stock vendible.",
            ),
        ),
    ]
