# Generated by Django 5.2.12 on 2026-07-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_salereturnline_restock"),
    ]

    operations = [
        migrations.AddField(
            model_name="salereturn",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Completada en"
            ),
        ),
    ]
