# Generated by Django 5.2.12 on 2026-08-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_rectifications_and_sale_line_traceability"),
        ("sales", "0004_saleline_tax_snapshot_salereturn_approved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="salereturn",
            name="original_billing_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="anchored_sale_returns",
                to="billing.billingdocument",
                verbose_name="Documento fiscal original",
            ),
        ),
    ]
