# Generated by Django 5.2.12 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0005_salereturn_original_billing_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleline",
            name="category_name",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Nombre de categoría congelado en el momento de la venta.",
                max_length=150,
                verbose_name="Nombre de la categoría",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="saleline",
            name="category_slug",
            field=models.SlugField(
                blank=True,
                default="",
                editable=False,
                help_text="Slug de categoría congelado en el momento de la venta.",
                max_length=150,
                verbose_name="Slug de la categoría",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="saleline",
            name="category_source_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                editable=False,
                help_text=(
                    "Identificador escalar de la categoría en el momento de la venta."
                ),
                null=True,
                verbose_name="ID de la categoría original",
            ),
        ),
    ]
