# Generated by Django 5.2.12 on 2026-07-22 18:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[("person", "Persona"), ("company", "Empresa")],
                        default="person",
                        max_length=20,
                        verbose_name="Tipo de cliente",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre completo o nombre comercial mostrado en el TPV.",
                        max_length=180,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre fiscal utilizado en facturas completas.",
                        max_length=180,
                        verbose_name="Nombre o razón social fiscal",
                    ),
                ),
                (
                    "tax_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Identificador fiscal nacional, si corresponde.",
                        max_length=30,
                        verbose_name="NIF/CIF/NIE",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        default="ES",
                        help_text="Código ISO de dos letras. Ejemplos: ES, PT o FR.",
                        max_length=2,
                        verbose_name="Código de país",
                    ),
                ),
                (
                    "foreign_id_type",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de identificación extranjera, si corresponde.",
                        max_length=50,
                        verbose_name="Tipo de documento extranjero",
                    ),
                ),
                (
                    "foreign_id",
                    models.CharField(
                        blank=True,
                        help_text="Número del documento extranjero, si corresponde.",
                        max_length=50,
                        verbose_name="Identificador extranjero",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Teléfono"
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="Código postal"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Provincia"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desactiva al cliente sin eliminar su histórico.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="core.business",
                        verbose_name="Negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        help_text="Saldo actual. Positivo significa deuda; negativo saldo a favor.",
                        max_digits=12,
                        verbose_name="Saldo pendiente",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Máxima deuda permitida para nuevas ventas a cuenta.",
                        max_digits=12,
                        verbose_name="Límite de crédito",
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="Impide generar nuevos cargos en esta cuenta.",
                        verbose_name="Ventas a cuenta bloqueadas",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_accounts",
                        to="core.business",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account",
                        to="customers.customer",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta de cliente",
                "verbose_name_plural": "Cuentas de clientes",
                "ordering": ["customer__name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAccountEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("charge", "Cargo"),
                            ("payment", "Pago"),
                            ("refund", "Reembolso"),
                            ("adjustment", "Ajuste"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de movimiento",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Variación aplicada al saldo. Nunca puede ser cero.",
                        max_digits=12,
                        verbose_name="Importe del movimiento",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Fotografía del saldo tras aplicar este movimiento.",
                        max_digits=12,
                        verbose_name="Saldo después del movimiento",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="customers.customeraccount",
                        verbose_name="Cuenta de cliente",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_account_entries",
                        to="core.business",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_account_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de cuenta de cliente",
                "verbose_name_plural": "Movimientos de cuentas de clientes",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["business", "is_active", "name"],
                name="idx_cust_bus_active_name",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["business", "tax_identifier"], name="idx_cust_bus_taxid"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tax_identifier", ""), _negated=True),
                fields=("business", "tax_identifier"),
                name="uniq_cust_bus_taxid",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("foreign_id", ""), _negated=True),
                fields=("business", "country_code", "foreign_id_type", "foreign_id"),
                name="uniq_cust_bus_foreign_id",
            ),
        ),
        migrations.AddIndex(
            model_name="customeraccount",
            index=models.Index(
                fields=["business", "is_blocked"], name="idx_custacc_bus_blocked"
            ),
        ),
        migrations.AddConstraint(
            model_name="customeraccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("credit_limit__gte", 0)),
                name="chk_custacc_credit_gte_0",
            ),
        ),
        migrations.AddIndex(
            model_name="customeraccountentry",
            index=models.Index(
                fields=["business", "account", "created_at"],
                name="idx_custentry_acc_created",
            ),
        ),
        migrations.AddIndex(
            model_name="customeraccountentry",
            index=models.Index(
                fields=["business", "entry_type", "created_at"],
                name="idx_custentry_bus_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="customeraccountentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True),
                name="chk_custentry_amount_not_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="customeraccountentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("entry_type", "charge"), ("amount__gt", 0), _connector="AND"
                )
                | models.Q(
                    ("entry_type__in", ["payment", "refund"]),
                    ("amount__lt", 0),
                    _connector="AND",
                )
                | (
                    models.Q(("entry_type", "adjustment"))
                    & models.Q(("amount", 0), _negated=True)
                ),
                name="chk_custentry_type_sign",
            ),
        ),
    ]
