# Generated by Django 5.2.12 on 2026-07-22 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customer",
            name="customers_unique_foreign_id_business",
        ),
        migrations.AlterField(
            model_name="customer",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                related_query_name="%(app_label)s_%(class)s",
                to="core.business",
            ),
        ),
        migrations.AlterField(
            model_name="customeraccount",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                related_query_name="%(app_label)s_%(class)s",
                to="core.business",
            ),
        ),
        migrations.AlterField(
            model_name="customeraccountentry",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                related_query_name="%(app_label)s_%(class)s",
                to="core.business",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("foreign_id_type", ""), _negated=True),
                    models.Q(("foreign_id", ""), _negated=True),
                ),
                fields=("business", "foreign_id_type", "foreign_id"),
                name="customers_unique_foreign_id_business",
            ),
        ),
    ]
