# Generated by Django 5.2.12 on 2026-07-22 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customeraccountentry",
            name="chk_custentry_type_sign",
        ),
        migrations.AddConstraint(
            model_name="customeraccountentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("amount__gt", 0), ("entry_type", "charge")),
                    models.Q(
                        ("amount__lt", 0), ("entry_type__in", ["payment", "refund"])
                    ),
                    models.Q(
                        ("entry_type", "adjustment"),
                        models.Q(("amount", 0), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="chk_custentry_type_sign",
            ),
        ),
    ]
