# Generated by Django 5.2.12 on 2026-08-18 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("customers", "0004_customeraccountentry_payment"),
        ("payments", "0002_seed_mvp_methods"),
        ("sales", "0004_saleline_tax_snapshot_salereturn_approved_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="customeraccountentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("payment__isnull", False)),
                fields=("payment",),
                name="uniq_custentry_payment_not_null",
            ),
        ),
    ]
