services:
  - type: web
    name: sala-tpv
    runtime: python
    plan: free

    buildCommand: bash ./build.sh

    startCommand: uv run gunicorn config.wsgi:application --bind 0.0.0.0:$PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.12

      - key: UV_PYTHON_DOWNLOADS
        value: never

      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production

      - key: SECRET_KEY
        sync: false

      - key: DATABASE_URL
        sync: false

      - key: ALLOWED_HOSTS
        sync: false

      - key: CSRF_TRUSTED_ORIGINS
        sync: false

      - key: LOG_LEVEL
        value: INFO

      - key: MEDIA_STORAGE_ENDPOINT_URL
        sync: false
      - key: MEDIA_STORAGE_ACCESS_KEY
        sync: false
      - key: MEDIA_STORAGE_SECRET_KEY
        sync: false
      - key: MEDIA_STORAGE_BUCKET_NAME
        sync: false
      - key: MEDIA_STORAGE_REGION
        sync: false
      - key: MEDIA_STORAGE_CUSTOM_DOMAIN
        sync: false
      - key: MEDIA_STORAGE_PUBLIC_READ
        sync: false