# Generated by Django 5.2.12 on 2026-08-26 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        ("cash_register", "0006_strengthen_cashmovement_origin"),
        ("core", "0001_initial"),
        ("customers", "0005_customeraccountentry_uniq_custentry_payment_not_null"),
        ("sales", "0004_saleline_tax_snapshot_salereturn_approved_by"),
        ("stores", "0005_store_is_default_alter_store_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="billingdocument",
            name="chk_billdoc_draft_issued_shape",
        ),
        migrations.AddConstraint(
            model_name="billingdocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("issued_at__isnull", True),
                        ("number__isnull", True),
                        ("status", "draft"),
                    ),
                    models.Q(
                        ("idempotency_key__isnull", False),
                        ("issued_at__isnull", False),
                        ("issued_by__isnull", False),
                        ("number__isnull", False),
                        ("operation_date__isnull", False),
                        ("status", "issued"),
                        models.Q(("series_text", ""), _negated=True),
                        models.Q(("idempotency_fingerprint", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="chk_billdoc_draft_issued_shape",
            ),
        ),
    ]
