# Generated by Django 5.2.12 on 2026-08-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "billing",
            "0002_remove_billingdocument_chk_billdoc_draft_issued_shape_and_more",
        ),
        ("sales", "0004_saleline_tax_snapshot_salereturn_approved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingdocument",
            name="rectification_method",
            field=models.CharField(
                blank=True,
                choices=[("I", "Por diferencias"), ("S", "Por sustitución")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="billingdocument",
            name="sale_return",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_documents",
                to="sales.salereturn",
            ),
        ),
        migrations.AddField(
            model_name="billingdocumentline",
            name="source_sale_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_document_lines",
                to="sales.saleline",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingdocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("document_type__in", ["F1", "F2", "F3"]),
                        ("rectification_method__isnull", True),
                    ),
                    models.Q(
                        ("document_type__in", ["R1", "R2", "R3", "R4", "R5"]),
                        ("rectification_method__in", ["I", "S"]),
                    ),
                    _connector="OR",
                ),
                name="chk_billdoc_rectification_method",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingdocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("document_type__in", ["R1", "R2", "R3", "R4", "R5"]),
                    ("sale_return__isnull", False),
                ),
                fields=("sale_return",),
                name="uniq_billdoc_return_rectification",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingdocumentline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_sale_line__isnull", False)),
                fields=("billing_document", "source_sale_line"),
                name="uniq_billline_document_source",
            ),
        ),
    ]
