# Generated by Django 5.2.12 on 2026-08-21 15:54

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_register", "0001_initial"),
        ("core", "0001_initial"),
        ("payments", "0002_seed_mvp_methods"),
        ("sales", "0004_saleline_tax_snapshot_salereturn_approved_by"),
        ("stores", "0005_store_is_default_alter_store_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counted_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Efectivo contado",
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Efectivo esperado",
                    ),
                ),
                (
                    "difference_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Diferencia"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
            ],
            options={
                "verbose_name": "Arqueo de caja",
                "verbose_name_plural": "Arqueos de caja",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="CashMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("sale_cash", "Cobro de venta en efectivo"),
                            ("refund_cash", "Reembolso en efectivo"),
                            ("cash_in", "Entrada manual de efectivo"),
                            ("cash_out", "Salida manual de efectivo"),
                            ("adjustment", "Ajuste"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tipo de movimiento",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Siempre se almacena positivo. El tipo indica entrada o salida.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Importe",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot del efectivo esperado después de aplicar este movimiento.",
                        max_digits=14,
                        verbose_name="Efectivo esperado después",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Motivo")),
            ],
            options={
                "verbose_name": "Movimiento de caja",
                "verbose_name_plural": "Movimientos de caja",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.AlterModelOptions(
            name="cashregister",
            options={
                "ordering": ("name", "pk"),
                "verbose_name": "Caja",
                "verbose_name_plural": "Cajas",
            },
        ),
        migrations.AlterModelOptions(
            name="cashsession",
            options={
                "ordering": ("-opened_at", "-pk"),
                "verbose_name": "Sesión de caja",
                "verbose_name_plural": "Sesiones de caja",
            },
        ),
        migrations.AddField(
            model_name="cashregister",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Código corto de la caja dentro de la tienda. Ejemplo: CAJA-01.",
                max_length=30,
                null=True,
                verbose_name="Código",
            ),
        ),
        migrations.AddField(
            model_name="cashsession",
            name="counted_cash_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Efectivo contado",
            ),
        ),
        migrations.AddField(
            model_name="cashsession",
            name="difference_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Diferencia de efectivo",
            ),
        ),
        migrations.AddField(
            model_name="cashsession",
            name="expected_cash_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Efectivo esperado",
            ),
        ),
        migrations.AddField(
            model_name="cashsession",
            name="opening_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Efectivo inicial",
            ),
        ),
        migrations.AlterField(
            model_name="cashregister",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activa"),
        ),
        migrations.AlterField(
            model_name="cashregister",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="cashsession",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de cierre"
            ),
        ),
        migrations.AlterField(
            model_name="cashsession",
            name="opened_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha de apertura"
            ),
        ),
        migrations.AlterField(
            model_name="cashsession",
            name="status",
            field=models.CharField(
                choices=[("open", "Abierta"), ("closed", "Cerrada")],
                db_index=True,
                default="open",
                max_length=10,
                verbose_name="Estado",
            ),
        ),
        migrations.AddIndex(
            model_name="cashregister",
            index=models.Index(
                fields=["business", "store", "is_active"],
                name="idx_cashreg_bus_store_act",
            ),
        ),
        migrations.AddIndex(
            model_name="cashsession",
            index=models.Index(
                fields=["business", "store", "status"], name="idx_cashsess_bus_store_st"
            ),
        ),
        migrations.AddIndex(
            model_name="cashsession",
            index=models.Index(
                fields=["cash_register", "status"], name="idx_cashsess_reg_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="cashsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("cash_register",),
                name="uniq_cashsession_open_reg",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("opening_amount__gte", Decimal("0.00"))),
                name="chk_cashsession_opening_gte0",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("counted_cash_amount__isnull", True),
                    ("counted_cash_amount__gte", Decimal("0.00")),
                    _connector="OR",
                ),
                name="chk_cashsession_counted_gte0",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("closed_at__isnull", True),
                        ("closed_by__isnull", True),
                        ("counted_cash_amount__isnull", True),
                        ("difference_amount", Decimal("0.00")),
                        ("status", "open"),
                    ),
                    models.Q(
                        ("closed_at__isnull", False),
                        ("closed_by__isnull", False),
                        ("counted_cash_amount__isnull", False),
                        ("status", "closed"),
                    ),
                    _connector="OR",
                ),
                name="chk_cashsession_state_fields",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "open"),
                    (
                        "difference_amount",
                        django.db.models.expressions.CombinedExpression(
                            models.F("counted_cash_amount"),
                            "-",
                            models.F("expected_cash_amount"),
                        ),
                    ),
                    _connector="OR",
                ),
                name="chk_cashsession_difference",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closed_at__isnull", True),
                    ("closed_at__gte", models.F("opened_at")),
                    _connector="OR",
                ),
                name="chk_cashsession_dates",
            ),
        ),
        migrations.AddField(
            model_name="cashcount",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cash_counts",
                to="core.business",
            ),
        ),
        migrations.AddField(
            model_name="cashcount",
            name="cash_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="counts",
                to="cash_register.cashsession",
            ),
        ),
        migrations.AddField(
            model_name="cashcount",
            name="counted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_counts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cashcount",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_counts",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cash_movements",
                to="core.business",
            ),
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="cash_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="cash_register.cashsession",
            ),
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_movements_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_movements",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_movements",
                to="sales.sale",
            ),
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_movements",
                to="stores.store",
            ),
        ),
        migrations.AddIndex(
            model_name="cashcount",
            index=models.Index(
                fields=["business", "store", "cash_session"],
                name="idx_cashcount_bus_store_sess",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashcount",
            constraint=models.CheckConstraint(
                condition=models.Q(("counted_amount__gte", Decimal("0.00"))),
                name="chk_cashcount_counted_gte0",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashcount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "difference_amount",
                        django.db.models.expressions.CombinedExpression(
                            models.F("counted_amount"), "-", models.F("expected_amount")
                        ),
                    )
                ),
                name="chk_cashcount_difference",
            ),
        ),
        migrations.AddIndex(
            model_name="cashmovement",
            index=models.Index(
                fields=["business", "store", "cash_session"],
                name="idx_cashmov_bus_store_sess",
            ),
        ),
        migrations.AddIndex(
            model_name="cashmovement",
            index=models.Index(
                fields=["cash_session", "movement_type"], name="idx_cashmov_sess_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="cashmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", Decimal("0.00"))),
                name="chk_cashmovement_amount_gt0",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashmovement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("payment__isnull", False)),
                fields=("payment",),
                name="uniq_cashmovement_payment",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("movement_type__in", ("sale_cash", "refund_cash")),
                        ("payment__isnull", False),
                        ("sale__isnull", False),
                    ),
                    models.Q(
                        ("movement_type__in", ("cash_in", "cash_out")),
                        ("payment__isnull", True),
                        ("sale__isnull", True),
                    ),
                    ("movement_type", "adjustment"),
                    _connector="OR",
                ),
                name="chk_cashmovement_origin",
            ),
        ),
    ]
