# Generated by Django 5.2.12 on 2026-08-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cash_register",
            "0002_cashcount_cashmovement_alter_cashregister_options_and_more",
        ),
        ("core", "0001_initial"),
        ("stores", "0005_store_is_default_alter_store_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashregister",
            name="code",
            field=models.CharField(
                help_text="Código corto de la caja dentro de la tienda. Ejemplo: CAJA-01.",
                max_length=30,
                verbose_name="Código",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashregister",
            constraint=models.UniqueConstraint(
                fields=("store", "code"), name="uniq_cashreg_store_code"
            ),
        ),
    ]
