# Generated by Django 5.2.12 on 2026-04-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
            ],
            options={
                "verbose_name": "empresa",
                "verbose_name_plural": "empresas",
                "ordering": ("name",),
                "indexes": [
                    models.Index(
                        fields=["is_active", "name"], name="core_biz_active_name_idx"
                    )
                ],
            },
        ),
    ]
