# Generated by Django 5.2.12 on 2026-10-08 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_payment_completed_requires_cash_session"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="chk_payment_completed_session",
        ),
    ]
