# Generated by Django 5.2.12 on 2026-06-14 19:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("stores", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="customuser",
            name="pin_hash",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="PIN para acciones importantes"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="core.business",
            ),
        ),
        migrations.CreateModel(
            name="UserStoreAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_sell", models.BooleanField(default=True)),
                ("can_open_cash", models.BooleanField(default=False)),
                ("can_close_cash", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_store_accesses",
                        to="core.business",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_accesses",
                        to="stores.stores",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "acceso de usuario a tienda",
                "verbose_name_plural": "accesos de usuarios a tiendas",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="stores",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                through="users.UserStoreAccess",
                through_fields=("user", "store"),
                to="stores.stores",
            ),
        ),
        migrations.AddIndex(
            model_name="userstoreaccess",
            index=models.Index(
                fields=["business", "user", "is_active"],
                name="user_store_access_user_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userstoreaccess",
            index=models.Index(
                fields=["business", "store", "is_active"],
                name="user_store_access_store_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="userstoreaccess",
            constraint=models.UniqueConstraint(
                fields=("business", "user", "store"), name="unique_user_store_access"
            ),
        ),
    ]
