# Generated by Django 5.2.12 on 2026-06-25 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stores",
            "0004_store_address_line_1_store_address_line_2_store_city_and_more",
        ),
        ("users", "0002_customuser_date_joined_customuser_pin_hash_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="stores",
        ),
        migrations.AddField(
            model_name="customuser",
            name="store",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                through="users.UserStoreAccess",
                through_fields=("user", "store"),
                to="stores.store",
            ),
        ),
        migrations.AlterField(
            model_name="userstoreaccess",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_accesses",
                to="stores.store",
            ),
        ),
    ]
