# Generated by Django 5.2.12 on 2026-07-07 17:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0003_alter_product_options_and_more"),
        ("core", "0001_initial"),
        (
            "stores",
            "0004_store_address_line_1_store_address_line_2_store_city_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Cantidad física actual disponible en tienda o almacén.",
                        max_digits=14,
                        verbose_name="Stock actual",
                    ),
                ),
                (
                    "reserved_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Cantidad reservada para pedidos pendientes, si aplica.",
                        max_digits=14,
                        verbose_name="Stock reservado",
                    ),
                ),
                (
                    "minimum_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Cantidad mínima recomendada antes de avisar reposición.",
                        max_digits=14,
                        verbose_name="Stock mínimo",
                    ),
                ),
                (
                    "maximum_stock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Cantidad máxima recomendada. Opcional.",
                        max_digits=14,
                        null=True,
                        verbose_name="Stock máximo",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Ejemplo: almacén, estantería, cámara, pasillo, etc.",
                        max_length=120,
                        verbose_name="Ubicación interna",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Permite desactivar el control de stock sin borrar histórico.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="core.business",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_items",
                        to="catalog.product",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_items",
                        to="stores.store",
                        verbose_name="Tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock de producto",
                "verbose_name_plural": "Stock de productos",
                "ordering": ["business", "store", "product__name"],
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Código interno del ajuste. Si se deja vacío, se genera automáticamente.",
                        max_length=40,
                        verbose_name="Código de ajuste",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("confirmed", "Confirmado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("stocktake", "Recuento de inventario"),
                            ("loss", "Pérdida o merma"),
                            ("breakage", "Rotura"),
                            ("error", "Error de stock"),
                            ("other", "Otro motivo"),
                        ],
                        default="stocktake",
                        max_length=30,
                        verbose_name="Motivo",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de confirmación"
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_adjustments",
                        to="core.business",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_stock_adjustments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Confirmado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_stock_adjustments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_adjustments",
                        to="stores.store",
                        verbose_name="Tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ajuste de stock",
                "verbose_name_plural": "Ajustes de stock",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockAdjustmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system_stock",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Stock que tenía el sistema antes del recuento.",
                        max_digits=14,
                        verbose_name="Stock en sistema",
                    ),
                ),
                (
                    "counted_stock",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Stock real contado físicamente.",
                        max_digits=14,
                        verbose_name="Stock contado",
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        editable=False,
                        help_text="Diferencia entre stock contado y stock en sistema.",
                        max_digits=14,
                        verbose_name="Diferencia",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=180, verbose_name="Notas"),
                ),
                (
                    "adjustment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.stockadjustment",
                        verbose_name="Ajuste",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustment_lines",
                        to="inventory.inventoryitem",
                        verbose_name="Stock afectado",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_adjustment_lines",
                        to="catalog.product",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de ajuste de stock",
                "verbose_name_plural": "Líneas de ajuste de stock",
                "ordering": ["product__name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("initial", "Inventario inicial"),
                            ("purchase_receipt", "Entrada por compra recibida"),
                            ("sale", "Salida por venta"),
                            ("sale_return", "Entrada por devolución de venta"),
                            ("purchase_return", "Salida por devolución a proveedor"),
                            ("adjustment_in", "Ajuste positivo"),
                            ("adjustment_out", "Ajuste negativo"),
                            ("transfer_in", "Entrada por traspaso"),
                            ("transfer_out", "Salida por traspaso"),
                            ("stocktake", "Regularización por recuento"),
                            ("loss", "Merma o pérdida"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de movimiento",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Cantidad movida. Siempre positiva.",
                        max_digits=14,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "stock_before",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Stock que había antes del movimiento.",
                        max_digits=14,
                        verbose_name="Stock antes",
                    ),
                ),
                (
                    "stock_after",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Stock resultante después del movimiento.",
                        max_digits=14,
                        verbose_name="Stock después",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Coste unitario asociado al movimiento, si aplica.",
                        max_digits=12,
                        null=True,
                        verbose_name="Coste unitario",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Manual"),
                            ("sale", "Venta"),
                            ("purchase", "Compra"),
                            ("transfer", "Traspaso"),
                            ("stock_adjustment", "Ajuste de stock"),
                            ("system", "Sistema"),
                        ],
                        help_text="Origen del movimiento: venta, compra, ajuste manual, etc.",
                        max_length=30,
                        verbose_name="Tipo de referencia",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="ID externo o interno del documento relacionado. Temporal hasta crear sales/purchases.",
                        max_length=80,
                        verbose_name="ID de referencia",
                    ),
                ),
                (
                    "operation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="Agrupa movimientos relacionados, por ejemplo un traspaso entre tiendas.",
                        verbose_name="ID de operación",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Motivo breve del movimiento.",
                        max_length=180,
                        verbose_name="Motivo",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del movimiento",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="core.business",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.inventoryitem",
                        verbose_name="Stock afectado",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="catalog.product",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "stock_adjustment_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="Línea de ajuste que originó el movimiento, si aplica.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="inventory.stockadjustmentline",
                        verbose_name="Línea de ajuste",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="stores.store",
                        verbose_name="Tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de stock",
                "verbose_name_plural": "Movimientos de stock",
                "ordering": ["-occurred_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["business", "store", "is_active"], name="idx_invitem_bus_store"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["business", "product"], name="idx_invitem_bus_prod"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["business", "current_stock"], name="idx_invitem_bus_stock"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.UniqueConstraint(
                fields=("business", "store", "product"),
                name="uniq_invitem_bus_store_prod",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_stock__gte", 0)),
                name="chk_invitem_cur_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_stock__gte", 0)),
                name="chk_invitem_res_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_stock__gte", 0)),
                name="chk_invitem_min_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("maximum_stock__isnull", True),
                    ("maximum_stock__gte", 0),
                    _connector="OR",
                ),
                name="chk_invitem_max_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_stock__lte", models.F("current_stock"))),
                name="chk_invitem_res_lte_cur",
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["business", "store", "status"], name="idx_stadj_bus_store_st"
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["business", "created_at"], name="idx_stadj_bus_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustment",
            constraint=models.UniqueConstraint(
                fields=("business", "code"), name="uniq_stadj_bus_code"
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustmentline",
            index=models.Index(
                fields=["adjustment", "product"], name="idx_stadjline_adj_prod"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustmentline",
            constraint=models.UniqueConstraint(
                fields=("adjustment", "inventory_item"), name="uniq_stadjline_adj_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustmentline",
            constraint=models.CheckConstraint(
                condition=models.Q(("system_stock__gte", 0)),
                name="chk_stadjline_sys_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustmentline",
            constraint=models.CheckConstraint(
                condition=models.Q(("counted_stock__gte", 0)),
                name="chk_stadjline_cnt_gte_0",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["business", "store", "occurred_at"],
                name="idx_stmov_bus_store_dt",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["business", "product", "occurred_at"],
                name="idx_stmov_bus_prod_dt",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["operation_id"], name="idx_stmov_operation"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["reference_type", "reference_id"], name="idx_stmov_reference"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="chk_stmov_qty_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_before__gte", 0)),
                name="chk_stmov_before_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_after__gte", 0)),
                name="chk_stmov_after_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unit_cost__isnull", True), ("unit_cost__gte", 0), _connector="OR"
                ),
                name="chk_stmov_cost_gte_0",
            ),
        ),
    ]
