# Generated by Django 5.2.12 on 2026-07-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inventoryitem",
            name="chk_invitem_cur_gte_0",
        ),
        migrations.RemoveConstraint(
            model_name="inventoryitem",
            name="chk_invitem_res_lte_cur",
        ),
        migrations.RemoveConstraint(
            model_name="stockmovement",
            name="chk_stmov_before_gte_0",
        ),
        migrations.RemoveConstraint(
            model_name="stockmovement",
            name="chk_stmov_after_gte_0",
        ),
        migrations.RemoveConstraint(
            model_name="stockadjustmentline",
            name="chk_stadjline_sys_gte_0",
        ),
    ]
