# Generated by Django 5.2 on 2026-09-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("stores", "0005_store_is_default_alter_store_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=100)),
                ("module", models.CharField(max_length=50)),
                (
                    "entity_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "entity_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("message", models.TextField()),
                ("old_payload", models.JSONField(blank=True, null=True)),
                ("new_payload", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_auditevent_set",
                        related_query_name="audit_auditevent",
                        to="core.business",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="stores.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "indexes": [
                    models.Index(
                        fields=["business", "-created_at"],
                        name="audit_biz_created_idx",
                    ),
                    models.Index(
                        fields=["business", "module", "-created_at"],
                        name="audit_biz_module_idx",
                    ),
                    models.Index(
                        fields=["business", "event_type", "-created_at"],
                        name="audit_biz_event_idx",
                    ),
                    models.Index(
                        fields=["business", "store", "-created_at"],
                        name="audit_biz_store_idx",
                    ),
                    models.Index(
                        fields=["business", "user", "-created_at"],
                        name="audit_biz_user_idx",
                    ),
                    models.Index(
                        fields=["business", "entity_type", "entity_id"],
                        name="audit_biz_entity_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("entity_id__isnull", True),
                            ("entity_type__isnull", True),
                        )
                        | models.Q(
                            ("entity_id__isnull", False),
                            ("entity_type__isnull", False),
                        ),
                        name="audit_entity_reference_pair",
                    )
                ],
            },
        )
    ]
