# Generated by Django 5.2.12 on 2026-06-15 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stores",
            options={
                "ordering": ("business", "name"),
                "verbose_name": "tienda",
                "verbose_name_plural": "tiendas",
            },
        ),
        migrations.AddField(
            model_name="stores",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stores",
                to="core.business",
            ),
        ),
        migrations.AddField(
            model_name="stores",
            name="code",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Código de tienda"
            ),
        ),
        migrations.AddField(
            model_name="stores",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activa"),
        ),
        migrations.AlterField(
            model_name="stores",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nombre de la tienda"),
        ),
        migrations.AddIndex(
            model_name="stores",
            index=models.Index(
                fields=["business", "is_active"], name="stores_biz_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stores",
            index=models.Index(fields=["business", "code"], name="stores_biz_code_idx"),
        ),
        migrations.AddIndex(
            model_name="stores",
            index=models.Index(fields=["business", "name"], name="stores_biz_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="stores",
            constraint=models.UniqueConstraint(
                fields=("business", "code"), name="unique_store_code_per_business"
            ),
        ),
        migrations.AddConstraint(
            model_name="stores",
            constraint=models.UniqueConstraint(
                fields=("business", "name"), name="unique_store_name_per_business"
            ),
        ),
    ]
