# Generated by Django 5.2.12 on 2026-06-21 20:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0002_alter_stores_options_stores_business_stores_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stores",
            name="address_line_1",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Dirección Principal"
            ),
        ),
        migrations.AddField(
            model_name="stores",
            name="address_line_2",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Dirección Secundaria"
            ),
        ),
        migrations.AddField(
            model_name="stores",
            name="city",
            field=models.CharField(blank=True, max_length=120, verbose_name="Ciudad"),
        ),
        migrations.AddField(
            model_name="stores",
            name="country_code",
            field=models.CharField(
                default="ES", max_length=2, verbose_name="Código país ISO"
            ),
        ),
        migrations.AddField(
            model_name="stores",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stores",
            name="email_store",
            field=models.EmailField(
                blank=True, max_length=120, verbose_name="email de la tienda"
            ),
        ),
        migrations.AddField(
            model_name="stores",
            name="phone_store",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Teléfono de la tienda"
            ),
        ),
        migrations.AddField(
            model_name="stores",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Código Postal"
            ),
        ),
        migrations.AddField(
            model_name="stores",
            name="province",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Provincia"
            ),
        ),
        migrations.AddField(
            model_name="stores",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
