# Generated by Django 5.2.12 on 2026-06-25 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0003_rename_stores_to_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="address_line_1",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Dirección Principal"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="address_line_2",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Dirección Secundaria"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="city",
            field=models.CharField(blank=True, max_length=120, verbose_name="Ciudad"),
        ),
        migrations.AddField(
            model_name="store",
            name="country_code",
            field=models.CharField(
                default="ES", max_length=2, verbose_name="Código país ISO"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="store",
            name="email_store",
            field=models.EmailField(
                blank=True, max_length=120, verbose_name="email de la tienda"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="phone_store",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Teléfono de la tienda"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Código Postal"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="province",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Provincia"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="code",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Código de tienda"
            ),
        ),
    ]
