# Generated by Django 5.2.12 on 2026-07-25 15:35

from django.db import migrations, models
from django.utils.text import slugify


def _build_base_code(business_name, store_name):
    business_slug = slugify((business_name or ""))[:10].upper().replace("-", "")
    store_slug = slugify((store_name or ""))[:10].upper().replace("-", "")

    if not business_slug:
        business_slug = "BUSINESS"

    if not store_slug:
        store_slug = "STORE"

    base_code = f"{business_slug}-{store_slug}"[:20]

    if base_code.endswith("-"):
        base_code = base_code[:-1]

    return base_code or "STORE"


def _forward_backfill_stores(apps, schema_editor):
    Store = apps.get_model("stores", "Store")
    db_alias = schema_editor.connection.alias

    used_codes_by_business = {}

    existing_codes_qs = Store.objects.using(db_alias).order_by("business_id", "pk")
    for store in existing_codes_qs:
        if not store.business_id:
            continue

        used_codes = used_codes_by_business.setdefault(store.business_id, set())
        current_code = (store.code or "").strip().upper()

        if current_code:
            used_codes.add(current_code)

    empty_code_qs = (
        Store.objects.using(db_alias)
        .select_related("business")
        .filter(models.Q(code__isnull=True) | models.Q(code=""))
        .order_by("business_id", "name", "pk")
    )

    for store in empty_code_qs:
        if not store.business_id:
            continue

        used_codes = used_codes_by_business.setdefault(store.business_id, set())

        business_name = getattr(store.business, "name", "")
        base_code = _build_base_code(business_name, store.name)

        candidate_code = base_code
        counter = 2

        while candidate_code in used_codes:
            suffix = f"-{counter}"
            max_base_len = 20 - len(suffix)
            candidate_code = f"{base_code[:max_base_len]}{suffix}"
            counter += 1

        store.code = candidate_code
        store.save(update_fields=["code"])
        used_codes.add(candidate_code)

    business_ids = (
        Store.objects.using(db_alias)
        .exclude(business_id__isnull=True)
        .values_list("business_id", flat=True)
        .distinct()
    )

    for business_id in business_ids:
        active_qs = Store.objects.using(db_alias).filter(
            business_id=business_id,
            is_active=True,
        )

        chosen_default = (
            active_qs.filter(is_default=True).order_by("name", "pk").first()
        )

        if chosen_default is None:
            chosen_default = active_qs.order_by("name", "pk").first()

        if chosen_default is None:
            Store.objects.using(db_alias).filter(
                business_id=business_id,
                is_default=True,
            ).update(is_default=False)
            continue

        Store.objects.using(db_alias).filter(
            business_id=business_id,
            is_default=True,
        ).exclude(pk=chosen_default.pk).update(is_default=False)

        if not chosen_default.is_default:
            Store.objects.using(db_alias).filter(pk=chosen_default.pk).update(
                is_default=True,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        (
            "stores",
            "0004_store_address_line_1_store_address_line_2_store_city_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_default",
            field=models.BooleanField(
                default=False, verbose_name="Tienda predeterminada"
            ),
        ),
        migrations.RunPython(
            _forward_backfill_stores,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="store",
            name="code",
            field=models.CharField(max_length=20, verbose_name="Código de tienda"),
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("code__isnull", False), models.Q(("code", ""), _negated=True)
                ),
                name="store_code_not_null_or_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_default", False), ("is_active", True), _connector="OR"
                ),
                name="store_default_requires_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("business",),
                name="unique_default_store_per_business",
            ),
        ),
    ]
