# Generated by Django 5.2.12 on 2026-07-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        (
            "stores",
            "0004_store_address_line_1_store_address_line_2_store_city_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_default",
            field=models.BooleanField(
                default=False, verbose_name="Tienda predeterminada"
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="code",
            field=models.CharField(max_length=20, verbose_name="Código de tienda"),
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("code__isnull", False), models.Q(("code", ""), _negated=True)
                ),
                name="store_code_not_null_or_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_default", False), ("is_active", True), _connector="OR"
                ),
                name="store_default_requires_active",
            ),
        ),
    ]
