# Generated by Django 5.2.12 on 2026-04-09 17:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legal_name",
                    models.CharField(max_length=150, verbose_name="razón social"),
                ),
                (
                    "tax_identifier",
                    models.CharField(blank=True, max_length=20, verbose_name="NIF/CIF"),
                ),
                (
                    "trade_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="nombre comercial"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="web")),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="dirección"
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="dirección extra"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="código postal"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="ciudad"),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="provincia"
                    ),
                ),
                (
                    "country_code",
                    models.CharField(default="ES", max_length=2, verbose_name="país"),
                ),
                (
                    "currency_code",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="moneda"
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(blank=True, max_length=150, verbose_name="marca"),
                ),
                ("logo_url", models.URLField(blank=True, verbose_name="logo")),
                (
                    "receipt_footer",
                    models.TextField(blank=True, verbose_name="pie de ticket"),
                ),
                (
                    "return_policy",
                    models.TextField(
                        blank=True, verbose_name="política de devoluciones"
                    ),
                ),
                (
                    "default_tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("21.00"),
                        help_text="IVA por defecto del negocio. Se usa como fallback si el producto o servicio no tiene un impuesto específico.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="IVA por defecto",
                    ),
                ),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="core.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil de negocio",
                "verbose_name_plural": "perfiles de negocio",
            },
        ),
        migrations.CreateModel(
            name="POSSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prices_include_tax",
                    models.BooleanField(
                        default=True,
                        help_text="Solo afecta a la visualización/interpretación comercial del precio. No cambia cómo se almacena el precio base.",
                        verbose_name="mostrar precios con IVA",
                    ),
                ),
                (
                    "allow_sale_without_stock",
                    models.BooleanField(
                        default=False, verbose_name="permitir venta sin stock"
                    ),
                ),
                (
                    "allow_manual_price",
                    models.BooleanField(
                        default=False, verbose_name="permitir precio manual"
                    ),
                ),
                (
                    "allow_manual_discounts",
                    models.BooleanField(
                        default=True, verbose_name="permitir descuentos manuales"
                    ),
                ),
                (
                    "max_manual_discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="descuento manual máximo %",
                    ),
                ),
                (
                    "require_open_cash_register",
                    models.BooleanField(
                        default=True, verbose_name="requiere caja abierta"
                    ),
                ),
                (
                    "allow_split_payments",
                    models.BooleanField(
                        default=True, verbose_name="permitir pagos divididos"
                    ),
                ),
                (
                    "require_pin_for_sensitive_actions",
                    models.BooleanField(
                        default=True, verbose_name="requerir PIN en acciones sensibles"
                    ),
                ),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pos_settings",
                        to="core.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "configuración TPV",
                "verbose_name_plural": "configuraciones TPV",
            },
        ),
    ]
