# Generated by Django 5.2.12 on 2026-06-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_config", "0002_backfill_business_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="possettings",
            name="allow_manual_price",
            field=models.BooleanField(
                default=True, verbose_name="permitir precio manual"
            ),
        ),
        migrations.AlterField(
            model_name="possettings",
            name="require_pin_for_sensitive_actions",
            field=models.BooleanField(
                default=False, verbose_name="requerir PIN en acciones sensibles"
            ),
        ),
    ]
