# Generated by Django 5.2.12 on 2026-06-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_config", "0003_alter_possettings_allow_manual_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprofile",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="phone",
            field=models.CharField(max_length=30, verbose_name="teléfono"),
        ),
    ]
