# Generated by Django 5.2.12 on 2026-06-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_config", "0004_alter_businessprofile_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="possettings",
            name="enable_stock_control",
            field=models.BooleanField(
                default=True, verbose_name="activar control de stock"
            ),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="address_line_1",
            field=models.CharField(max_length=255, verbose_name="dirección"),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="city",
            field=models.CharField(max_length=100, verbose_name="ciudad"),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="postal_code",
            field=models.CharField(max_length=12, verbose_name="código postal"),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="province",
            field=models.CharField(max_length=100, verbose_name="provincia"),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="tax_identifier",
            field=models.CharField(max_length=20, verbose_name="NIF/CIF"),
        ),
        migrations.AlterField(
            model_name="possettings",
            name="require_pin_for_sensitive_actions",
            field=models.BooleanField(
                default=True, verbose_name="requerir PIN en acciones sensibles"
            ),
        ),
    ]
