# Generated by Django 5.2.12 on 2026-06-28 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Nombre de la categoria"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=150,
                        verbose_name="Etiqueta de la categoria",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="Orden visual"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        verbose_name="Esta activa la categoria?",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="core.business",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="Categoría padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Ejemplo: IVA 21%, IVA 10%, IVA 4%, Exento IVA art. 20.",
                        max_length=100,
                        verbose_name="Nombre del impuesto",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Ejemplo: IVA_21, IVA_10, IVA_4, EXENTO_E1.",
                        max_length=30,
                        verbose_name="Código interno del impuesto",
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("IVA", "IVA - Impuesto sobre el Valor Añadido"),
                            ("IGIC", "IGIC - Canarias"),
                            ("IPSI", "IPSI - Ceuta/Melilla"),
                            ("OTHER", "Otro impuesto"),
                        ],
                        default="IVA",
                        help_text="Normalmente IVA para península/Baleares.",
                        max_length=20,
                        verbose_name="Tipo de impuesto",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ejemplo: 21.00, 10.00, 4.00, 0.00.",
                        max_digits=5,
                        verbose_name="Porcentaje impositivo",
                    ),
                ),
                (
                    "clave_regimen",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("01", "01 - Operación de régimen general"),
                            ("02", "02 - Exportación"),
                            (
                                "03",
                                "03 - Régimen especial de bienes usados, arte, antigüedades y colección",
                            ),
                            ("04", "04 - Régimen especial del oro de inversión"),
                            ("05", "05 - Régimen especial de agencias de viajes"),
                            ("06", "06 - Grupo de entidades en IVA"),
                            ("07", "07 - Régimen especial del criterio de caja"),
                            ("08", "08 - Operaciones sujetas a IPSI/IGIC"),
                            (
                                "09",
                                "09 - Agencias de viaje mediadoras en nombre y por cuenta ajena",
                            ),
                            ("10", "10 - Cobros por cuenta de terceros"),
                            ("11", "11 - Arrendamiento de local de negocio"),
                            (
                                "14",
                                "14 - IVA pendiente de devengo en certificaciones de obra pública",
                            ),
                            (
                                "15",
                                "15 - IVA pendiente de devengo en operaciones de tracto sucesivo",
                            ),
                            ("17", "17 - OSS / IOSS"),
                            ("18", "18 - Recargo de equivalencia"),
                            (
                                "19",
                                "19 - Régimen especial de agricultura, ganadería y pesca",
                            ),
                            ("20", "20 - Régimen simplificado"),
                        ],
                        default="01",
                        help_text="Régimen fiscal aplicable. Para venta normal con IVA, usar 01.",
                        max_length=2,
                        null=True,
                        verbose_name="Clave de régimen",
                    ),
                ),
                (
                    "calificacion_operacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "S1",
                                "S1 - Sujeta y no exenta, sin inversión del sujeto pasivo",
                            ),
                            (
                                "S2",
                                "S2 - Sujeta y no exenta, con inversión del sujeto pasivo",
                            ),
                            ("N1", "N1 - No sujeta por artículo 7, 14 u otros"),
                            ("N2", "N2 - No sujeta por reglas de localización"),
                        ],
                        default="S1",
                        help_text="S1 para venta normal con IVA. S2 para inversión sujeto pasivo. N1/N2 para operaciones no sujetas.",
                        max_length=2,
                        null=True,
                        verbose_name="Calificación de la operación",
                    ),
                ),
                (
                    "operacion_exenta",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("E1", "E1 - Exenta por artículo 20"),
                            ("E2", "E2 - Exenta por artículo 21"),
                            ("E3", "E3 - Exenta por artículo 22"),
                            ("E4", "E4 - Exenta por artículos 23 y 24"),
                            ("E5", "E5 - Exenta por artículo 25"),
                            ("E6", "E6 - Exenta por otros"),
                        ],
                        help_text="Solo se rellena si la operación está exenta. Ejemplo: E1 para exenta por artículo 20.",
                        max_length=2,
                        null=True,
                        verbose_name="Causa de operación exenta",
                    ),
                ),
                (
                    "has_equivalence_surcharge",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar solo si aplica recargo de equivalencia. Para MVP normal suele ser False.",
                        verbose_name="Tiene recargo de equivalencia",
                    ),
                ),
                (
                    "equivalence_surcharge_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Ejemplo: 5.20. Solo si has_equivalence_surcharge=True.",
                        max_digits=5,
                        null=True,
                        verbose_name="Porcentaje de recargo de equivalencia",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Solo debe haber un impuesto por defecto por negocio. Normalmente IVA 21%.",
                        verbose_name="Impuesto por defecto",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="No borrar impuestos usados históricamente. Desactivar si ya no se quiere usar.",
                        verbose_name="Impuesto activo",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes",
                        to="core.business",
                        verbose_name="Negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impuesto",
                "verbose_name_plural": "Impuestos",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre visible en catálogo, venta y ticket.",
                        max_length=180,
                        verbose_name="Nombre del producto",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Código interno del producto. Si se deja vacío, se generará automáticamente.",
                        max_length=80,
                        verbose_name="Código interno del producto",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Código de barras del producto. Si se deja vacío en productos físicos, se generará uno interno automáticamente. En servicios no se genera.",
                        max_length=80,
                        null=True,
                        verbose_name="Código de barras",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio base sin IVA. El precio con IVA se calcula en services/views según POSSettings.",
                        max_digits=12,
                        verbose_name="Precio base sin IVA",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Coste del producto para márgenes y reporting. No se usa para calcular el precio de venta.",
                        max_digits=12,
                        null=True,
                        verbose_name="Coste de compra",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("ud", "Unidad"),
                            ("kg", "Kilogramo"),
                            ("g", "Gramo"),
                            ("l", "Litro"),
                            ("m", "Metro"),
                            ("h", "Hora"),
                            ("servicio", "Servicio"),
                        ],
                        default="ud",
                        help_text="Unidad de venta: unidad, kg, hora, servicio, etc.",
                        max_length=20,
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "track_stock",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si este producto afecta al inventario. Los servicios normalmente no controlan stock.",
                        verbose_name="Controla stock",
                    ),
                ),
                (
                    "is_service",
                    models.BooleanField(
                        default=False,
                        help_text="Marca si no es un producto físico. Si es servicio, normalmente track_stock será False.",
                        verbose_name="Es un servicio",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si está desactivado no aparece para nuevas ventas. No borrar productos usados históricamente.",
                        verbose_name="Disponible para venta",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="core.business",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Categoría comercial del producto. Opcional.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        blank=True,
                        help_text="Impuesto específico del producto. Si se deja vacío, se usará el impuesto por defecto del negocio.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.tax",
                        verbose_name="Impuesto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("business", "slug"), name="unique_category_slug_per_business"
            ),
        ),
        migrations.AddConstraint(
            model_name="tax",
            constraint=models.UniqueConstraint(
                fields=("business", "code"), name="unique_tax_code_per_business"
            ),
        ),
        migrations.AddConstraint(
            model_name="tax",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("business",),
                name="unique_default_tax_per_business",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("business", "sku"), name="unique_product_sku_per_business"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode__isnull", False)),
                fields=("business", "barcode"),
                name="unique_product_barcode_per_business",
            ),
        ),
    ]
