# Generated by Django 5.2.12 on 2026-06-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["business", "is_active", "sort_order", "name"],
                name="idx_cat_bus_active_ord",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["business", "is_active", "name"], name="idx_prod_bus_act_name"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["business", "category", "is_active"],
                name="idx_prod_bus_cat_act",
            ),
        ),
        migrations.AddIndex(
            model_name="tax",
            index=models.Index(
                fields=["business", "is_active"], name="idx_tax_business_active"
            ),
        ),
    ]
