# Generated by Django 5.2.12 on 2026-07-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_category_idx_cat_bus_active_ord_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="idx_prod_bus_cat_act",
        ),
        migrations.AddField(
            model_name="product",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Orden en el que se muestra el producto dentro de su categoría. Los números más bajos aparecen antes.",
                verbose_name="Orden visual",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["business", "category", "is_active", "sort_order", "name"],
                name="idx_prod_bus_cat_sort",
            ),
        ),
    ]
