# Generated by Django 5.2 on 2026-09-14

import decimal
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0003_alter_product_options_and_more"),
        ("core", "0001_initial"),
        ("stores", "0005_store_is_default_alter_store_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=180, verbose_name="Nombre comercial"),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="Razón social"
                    ),
                ),
                (
                    "tax_identifier",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Identificador fiscal"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Teléfono"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Dirección")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="core.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["name", "pk"],
                "indexes": [
                    models.Index(
                        fields=["business", "is_active", "name"],
                        name="idx_supplier_bus_active_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("ordered", "Pedida"),
                            ("partially_received", "Recibida parcialmente"),
                            ("received", "Recibida"),
                            ("cancelled", "Cancelada"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Referencia"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "ordered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha del pedido"
                    ),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        editable=False,
                        max_digits=14,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        editable=False,
                        max_digits=14,
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        editable=False,
                        max_digits=14,
                        verbose_name="Total",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="core.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="stores.store",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="purchases.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra",
                "verbose_name_plural": "Compras",
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["business", "store", "status"],
                        name="idx_purchase_bus_store_status",
                    ),
                    models.Index(
                        fields=["business", "supplier", "status"],
                        name="idx_purchase_bus_sup_status",
                    ),
                    models.Index(
                        fields=["business", "created_at"],
                        name="idx_purchase_bus_created",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("subtotal_amount__gte", decimal.Decimal("0.00"))
                        ),
                        name="chk_purchase_subtotal_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("tax_amount__gte", decimal.Decimal("0.00"))
                        ),
                        name="chk_purchase_tax_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("total_amount__gte", decimal.Decimal("0.00"))
                        ),
                        name="chk_purchase_total_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "total_amount",
                                models.F("subtotal_amount") + models.F("tax_amount"),
                            )
                        ),
                        name="chk_purchase_total_sum",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["draft", "cancelled"]),
                            ("ordered_at__isnull", False),
                            _connector="OR",
                        ),
                        name="chk_purchase_ordered_has_date",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchaseLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_name",
                    models.CharField(
                        max_length=180, verbose_name="Nombre del producto"
                    ),
                ),
                (
                    "sku",
                    models.CharField(blank=True, max_length=80, verbose_name="SKU"),
                ),
                ("unit", models.CharField(max_length=20, verbose_name="Unidad")),
                (
                    "quantity_ordered",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "quantity_received",
                    models.DecimalField(
                        decimal_places=3,
                        default=decimal.Decimal("0.000"),
                        editable=False,
                        max_digits=14,
                    ),
                ),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=decimal.Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "line_subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        editable=False,
                        max_digits=14,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        editable=False,
                        max_digits=14,
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        editable=False,
                        max_digits=14,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_lines",
                        to="core.business",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_lines",
                        to="catalog.product",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchases.purchase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de compra",
                "verbose_name_plural": "Líneas de compra",
                "ordering": ["created_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["business", "purchase"],
                        name="idx_purchline_bus_purchase",
                    ),
                    models.Index(
                        fields=["business", "product"], name="idx_purchline_bus_product"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("quantity_ordered__gt", decimal.Decimal("0.000"))
                        ),
                        name="chk_purchline_qty_ordered_gt_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("quantity_received__gte", decimal.Decimal("0.000"))
                        ),
                        name="chk_purchline_qty_received_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("quantity_received__lte", models.F("quantity_ordered"))
                        ),
                        name="chk_purchline_received_lte_ordered",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("unit_cost__gte", 0)),
                        name="chk_purchline_cost_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("tax_rate__gte", 0)),
                        name="chk_purchline_tax_rate_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("line_subtotal__gte", 0)),
                        name="chk_purchline_subtotal_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("tax_amount__gte", 0)),
                        name="chk_purchline_tax_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("line_total__gte", 0)),
                        name="chk_purchline_total_gte_0",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                ("idempotency_key", models.UUIDField()),
                ("idempotency_fingerprint", models.CharField(max_length=64)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_receipts",
                        to="core.business",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="purchases.purchase",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_receipts_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_receipts",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recepción de compra",
                "verbose_name_plural": "Recepciones de compra",
                "ordering": ["-received_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["business", "purchase", "received_at"],
                        name="idx_purchreceipt_bus_purchase",
                    ),
                    models.Index(
                        fields=["business", "store", "received_at"],
                        name="idx_purchreceipt_bus_store",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "idempotency_key"),
                        name="uniq_purchreceipt_bus_idem_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity_received",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_receipt_lines",
                        to="core.business",
                    ),
                ),
                (
                    "purchase_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_lines",
                        to="purchases.purchaseline",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchases.purchasereceipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de recepción de compra",
                "verbose_name_plural": "Líneas de recepción de compra",
                "ordering": ["created_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["business", "receipt"], name="idx_prec_line_bus_receipt"
                    ),
                    models.Index(
                        fields=["business", "purchase_line"],
                        name="idx_purchreceiptline_bus_line",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("quantity_received__gt", decimal.Decimal("0.000"))
                        ),
                        name="chk_purchreceiptline_qty_gt_0",
                    ),
                    models.UniqueConstraint(
                        fields=("receipt", "purchase_line"),
                        name="uniq_purchreceiptline_receipt_line",
                    ),
                ],
            },
        ),
    ]
